#!/usr/bin/env ruby

require_relative 'lib/toolbelt/deploy.rb'

server_name = File.exist?('.cloud66_stack') ? File.read('.cloud66_stack').chomp.strip : File.basename(Dir.pwd)
Toolbelt::Deploy.new(:staging, server_name: server_name).call

